#!/bin/bash

# Exit immediately on errors, and echo commands as they are executed.
set -ex

if [ -d "web/wp/wp-content/mu-plugins/" ]; then
  rsync -a web/wp/wp-content/mu-plugins/* web/wp-content/mu-plugins/
fi

if [ -f "web/wp/wp-config.php" ]; then
  rm web/wp/wp-config.php
fi

if [ -d "web/wp/wp-content" ]; then
  rm -rf web/wp/wp-content
fi

# Remove old Pantheon mu-plugin if it exists
# https://github.com/pantheon-systems/wordpress-composer/issues/29
if [ -d "web/wp-content/mu-plugins/pantheon/" ]; then
  rm -rf web/wp-content/mu-plugins/pantheon
fi

if [ -f "web/wp-content/mu-plugins/pantheon.php" ]; then
  rm web/wp-content/mu-plugins/pantheon.php
fi