#!/bin/bash

# Exit immediately on errors, and echo commands as they are executed.
set -ex

if [ -d "web/wp/wp-content/mu-plugins/" ]; then
  rsync -r web/wp/wp-content/mu-plugins/* web/wp-content/mu-plugins/
fi

if [ -f "web/wp/wp-config.php" ]; then
  rm web/wp/wp-config.php
fi

if [ -d "web/wp/wp-content" ]; then
  rm -rf web/wp/wp-content
fi

# Create empty .env in theme folder to prevent the phpdotenv error:
# “Failed to open stream: No such file or directory”
if [ -d web/wp-content/themes/sage/ ]; then
    if [ ! -f web/wp-content/themes/sage/.env ]; then
        echo "# Intentionally blank, DO NOT add env vars!" > web/wp-content/themes/sage/.env
    fi
fi
